import type { ResearchPaper } from "@/types/research"

export const seedResearchPapers: Omit<ResearchPaper, "id">[] = [
  {
    doi: "10.1136/bjsports-2017-097608",
    title: "Protein supplementation and resistance training gains",
    authors: "Morton RW et al.",
    journal: "BJSM",
    year: 2018,
    studyType: "Systematic Review",
    population: "Resistance-trained adults",
    qualityRating: 5,
    confidenceLevel: "STRONG",
    keyFindings: ["Higher protein (>1.6 g/kg) supports lean mass retention."],
    eli5Summary: "More protein helps protect muscle during dieting.",
    topics: ["protein", "muscle_gain"]
  },
  {
    doi: "10.1249/MSS.0000000000000852",
    title: "ACSM Position Stand: Nutrition and Athletic Performance",
    authors: "Thomas DT et al.",
    journal: "MSSE",
    year: 2016,
    studyType: "Position Stand",
    population: "Athletes",
    qualityRating: 5,
    confidenceLevel: "STRONG",
    keyFindings: ["Carbohydrate needs vary by training load."],
    eli5Summary: "More intense training needs more carbs.",
    topics: ["carbohydrates", "performance"]
  },
  {
    doi: "10.1016/j.jsbmb.2021.105948",
    title: "Low-fat diets and testosterone in men: systematic review",
    authors: "Whittaker J & Wu K",
    journal: "JSBMB",
    year: 2021,
    studyType: "Systematic Review",
    population: "Males",
    qualityRating: 5,
    confidenceLevel: "STRONG",
    keyFindings: ["Fat intake below 20% reduces testosterone."],
    eli5Summary: "Too little fat can hurt hormones.",
    topics: ["fat", "hormones"]
  },
  {
    doi: "10.1007/s40279-020-01316-1",
    title: "Low energy availability in athletes: a review",
    authors: "Logue DM et al.",
    journal: "Sports Medicine",
    year: 2020,
    studyType: "Review",
    population: "Athletes",
    qualityRating: 4,
    confidenceLevel: "STRONG",
    keyFindings: ["Energy availability thresholds predict RED-S risk."],
    eli5Summary: "Too little fuel hurts recovery and hormones.",
    topics: ["red_s", "energy_availability"]
  },
  {
    doi: "10.3390/jfmk9010008",
    title: "HRV applications in strength and conditioning",
    authors: "Plews DJ et al.",
    journal: "JFMK",
    year: 2024,
    studyType: "Review",
    population: "Strength athletes",
    qualityRating: 4,
    confidenceLevel: "MODERATE",
    keyFindings: ["HRV trends reflect recovery status."],
    eli5Summary: "HRV helps track readiness.",
    topics: ["hrv", "recovery"]
  },
  {
    doi: "10.1249/MSS.0000000000001528",
    title: "Protein timing and muscle growth meta-analysis",
    authors: "Schoenfeld BJ et al.",
    journal: "MSSE",
    year: 2013,
    studyType: "Meta-analysis",
    population: "Resistance-trained adults",
    qualityRating: 4,
    confidenceLevel: "MODERATE",
    keyFindings: ["Total daily protein matters more than timing."],
    eli5Summary: "Hit your daily protein first.",
    topics: ["protein", "timing"]
  },
  {
    doi: "10.3945/ajcn.2007.25080",
    title: "High-GI meals and sleep onset",
    authors: "Afaghi A et al.",
    journal: "AJCN",
    year: 2007,
    studyType: "RCT",
    population: "Healthy adults",
    qualityRating: 3,
    confidenceLevel: "MODERATE",
    keyFindings: ["High-GI carbs 4h pre-bed shorten sleep onset."],
    eli5Summary: "Evening carbs can help sleep.",
    topics: ["sleep", "carbohydrates"]
  },
  {
    doi: "10.1002/oby.21538",
    title: "Persistent metabolic adaptation after weight loss",
    authors: "Fothergill E et al.",
    journal: "Obesity",
    year: 2016,
    studyType: "Cohort",
    population: "Weight loss competitors",
    qualityRating: 4,
    confidenceLevel: "STRONG",
    keyFindings: ["Metabolic adaptation persists long term."],
    eli5Summary: "Metabolism can stay lower for years after dieting.",
    topics: ["metabolic_adaptation", "tdee"]
  },
  {
    doi: "10.1136/bjsports-2023-106586",
    title: "IOC consensus on RED-S",
    authors: "Mountjoy M et al.",
    journal: "BJSM",
    year: 2023,
    studyType: "Consensus",
    population: "Athletes",
    qualityRating: 5,
    confidenceLevel: "STRONG",
    keyFindings: ["Sex-specific energy availability thresholds."],
    eli5Summary: "RED-S risk depends on fuel availability.",
    topics: ["red_s", "energy_availability"]
  },
  {
    doi: "10.1080/02640414.2011.585473",
    title: "Energy availability in athletes",
    authors: "Loucks AB et al.",
    journal: "J Sports Sci",
    year: 2011,
    studyType: "Review",
    population: "Athletes",
    qualityRating: 4,
    confidenceLevel: "STRONG",
    keyFindings: ["Low EA impairs hormones and performance."],
    eli5Summary: "Low fuel availability hurts recovery.",
    topics: ["red_s", "energy_availability"]
  },
  {
    doi: "10.1186/s12970-014-0031-2",
    title: "Metabolic adaptation to weight loss",
    authors: "Trexler ET et al.",
    journal: "JISSN",
    year: 2014,
    studyType: "Review",
    population: "Athletes",
    qualityRating: 4,
    confidenceLevel: "MODERATE",
    keyFindings: ["Adaptation requires longer recovery timelines."],
    eli5Summary: "Reverse diets take time.",
    topics: ["reverse_diet", "metabolic_adaptation"]
  }
]

const filler = Array.from({ length: 39 }, (_, index) => ({
  doi: `10.1234/mip.2024.${index + 1}`,
  title: `Metabolic optimization insight ${index + 1}`,
  authors: "MIP Research Collective",
  journal: "MIP Research Digest",
  year: 2024,
  studyType: "Review",
  population: "Athletes",
  qualityRating: 3,
  confidenceLevel: "PRELIMINARY",
  keyFindings: ["Emerging evidence suggests individualized responses."],
  eli5Summary: "Early research points to personalized targets.",
  topics: ["metabolic_adaptation", "recovery"]
}))

seedResearchPapers.push(...filler)
